language: ruby
cache: bundler
rvm:
  - 2.3.1
sudo: false
branches:
  only:
    - master
bundler_args: --without=integration --path=.bundle
script:
  - bundle exec rake style
  - bundle exec rake spec
